source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'DevApp' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
end

target 'UnitTest' do
  pod 'GoogleMaps'
  pod 'OCMock'
  pod 'Google-Maps-iOS-Utils'
end
